### ISSUE TITLE
NameError: global name 'ShellCommandJob' is not defined

### ISSUE THREAD

**Issue by krull** [epuzanov/ZenPacks.community.DistributedCollectors#13]
Hello,

I don't know if this is related, but it seems the error is on DistributedCollectors. Check this output out:
```
2015-02-25 12:57:55,307 INFO zen.Job: Job 2d51d6b4-fd39-4c13-9611-64f1e4b10ab0 (ZenPacks.zenoss.XenServer.jobs.XenServerCreationJob) received
2015-02-25 12:57:55,318 INFO zen.Job: Beginning job Add XenServer Endpoint ZenPacks.zenoss.XenServer.jobs.XenServerCreationJob
2015-02-25 12:57:55,318 INFO zen.Job: Created XenServer endpoint device 192.168.1.1
2015-02-25 12:57:55,319 INFO zen.Device: device name '192.168.1.1' for ip '192.168.1.1'
2015-02-25 12:57:55,614 INFO zen.Device: 192.168.1.1's IP address has been set to 192.168.1.1.
2015-02-25 12:57:55,614 INFO zen.Device: setting title to '192.168.1.1'
2015-02-25 12:57:55,614 INFO zen.Device: setting tag to ''
2015-02-25 12:57:55,615 INFO zen.Device: setting serialNumber to ''
2015-02-25 12:57:55,616 INFO zen.Device: setting rackSlot to ''
2015-02-25 12:57:55,616 INFO zen.Device: setting productionState to 1000
2015-02-25 12:57:55,619 INFO zen.Device: setting priority to 3
2015-02-25 12:57:55,619 INFO zen.Device: setting comments to ''
2015-02-25 12:57:55,620 INFO zen.Device: setting performance monitor to 'localhost'
2015-02-25 12:57:55,704 INFO zen.Job: Waiting 40 seconds for ZenHub to learn about 192.168.1.1
2015-02-25 12:57:56,552 INFO zen.Job: Scheduling immediate modeling job for 192.168.1.2
2015-02-25 12:57:56,659 ERROR zen.Job: Job 8da2ac18-9b8b-4dbb-9e94-85ddf96ae4bc raised exception
2015-02-25 12:57:56,659 ERROR zen.Job: <traceback object at 0x7f88782b7b48>
2015-02-25 12:57:56,778 ERROR celery.worker.job: Task ZenPacks.zenoss.XenServer.jobs.XenServerCreationJob[8da2ac18-9b8b-4dbb-9e94-85ddf96ae4bc] raised exception: NameError("global name 'ShellCommandJob' is not defined",)
Traceback (most recent call last):
  File "/usr/local/zenoss/lib/python/celery/task/trace.py", line 186, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/zenoss/Products/Jobber/jobs.py", line 185, in _do_run
    result = _runjob()
  File "/usr/local/zenoss/lib/python/ZODB/transact.py", line 44, in g
    r = f(*args, **kwargs)
  File "/usr/local/zenoss/Products/Jobber/jobs.py", line 175, in _runjob
    result = self._run(*args, **kwargs)
  File "/usr/local/zenoss/ZenPacks/ZenPacks.zenoss.XenServer-1.1.0dev-py2.7.egg/ZenPacks/zenoss/XenServer/jobs.py", line 69, in _run
    return device.collectDevice(background=True)
  File "/usr/local/zenoss/Products/ZenModel/Device.py", line 1778, in collectDevice
    background, write)
  File "/usr/local/zenoss/Products/ZenModel/PerformanceConf.py", line 719, in collectDevice
    REQUEST, write)
  File "/usr/local/zenoss/ZenPacks/ZenPacks.community.DistributedCollectors-2.0.2-py2.7.egg/ZenPacks/community/DistributedCollectors/__init__.py", line 248, in _executeZenModelerCommand
    result = self.dmd.JobManager.addJob(ShellCommandJob,zenmodelerCmd)
NameError: global name 'ShellCommandJob' is not defined
```
I donno if ShellCommandJob is yours so I'll just put it here for now. I will research more on ShellCommandJob, and update this issue once I have more information.

**Comment by mhaswell-resilient** [comment]
I haven't used the XenServer plugin before so I can't really comment on this. Please provide further information with your error reports. Version of Zenoss, Version of linux. Can you model this XenServer from the main Zenoss system directly rather than via a distributed collector? It seems to be an internal Zenoss modelling issue so far. ShellCommandJob is part of Zenoss as per https://searchcode.com/codesearch/view/53206023/ .

**Comment by KimNorgaard** [comment]
I ran into the same issue when calling remodel via the REST API.

ShellCommandJob looks deprecated when you look at http://dev.zenoss.org/trac/browser/tags/zenoss-4.2.5/Products/Jobber/jobs.py

**Comment by jstanley23** [comment]
replace ShellCommandJob with SubprocessJob.

ShellCommandJob is deprecated.

**Comment by johnavp1989** [comment]
After speaking with the guys on IRC they were able to offer a workaround for this. Since ShellCommandJob is deprecated they asked me to use SubprocessJob instead. I replaced the two instances of ShellCommandJob with SubprocessJob in /ZenPacks/ZenPacks.community.DistributedCollectors/ZenPacks/community/DistributedCollectors/__init__.py and it's now working.
